###
# group: auth
# @name login/browser
POST {{host}}/login
Referer: {{referer}}
Accept: application/json
Content-Type: application/json

{
    "email": "user@example.com",
    "password": "123456"
}

> {%
    client.global.set("authToken", response.body.token);
%}

###
# group: user
# @name set-role
POST {{host}}/users/{{adminId}}/set-role
Accept: application/json
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "role": "USER"
}
